export const tips = [
    "Did you know? You can try different prompts for unique results.",
    "Tip: Experiment with different styles for creative outputs.",
    "Fun Fact: AI-generated art can be used for various creative projects!",
    "Did you know? You can combine multiple concepts in one prompt.",
    "Pro Tip: Use descriptive language for more accurate results.",
    "Creative Idea: Mix different genres for unexpected outcomes.",
    "Did you know? Short and concise prompts often work best.",
    "Fun Fact: AI art is transforming the world of digital creativity.",
    "Pro Tip: Choose a specific model for high-quality results.",
    "You can download your generated image once ready.",
    "Fun Fact: AI can generate art in styles inspired by famous artists!",
    "Tip: Use action words to generate dynamic and engaging images.",
    "Creative Idea: Generate abstract art by using ambiguous prompts.",
    "Did you know? You can create a series of images by varying one element in your prompts.",
    "Pro Tip: Specify colors and textures for more detailed images.",
    "Fun Fact: AI art can be used for custom prints and merchandise.",
    "Tip: Save your favorite prompts to use them again later.",
    "Creative Idea: Combine AI art with traditional art for unique pieces.",
    "Did you know? You can generate multiple images and choose the best one.",
    "Pro Tip: Use seasonal and thematic prompts for timely creations.",
    "Fun Fact: AI can generate art inspired by various cultures and traditions.",
    "Tip: Use adjectives to give more character to your prompts.",
    "Creative Idea: Create storyboards by generating sequential images.",
    "Did you know? You can create logos and branding assets using AI.",
    "Pro Tip: Use specific nouns to guide the AI towards your desired output.",
    "Fun Fact: AI-generated images can be used for book covers and illustrations.",
    "Tip: Try prompts that describe emotions for expressive art.",
    "Creative Idea: Generate art for use in social media posts and ads.",
    "Did you know? AI can help visualize complex concepts and ideas.",
    "Pro Tip: Use historical and futuristic prompts for interesting contrasts."
  ];
  